# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

schedules:
- cron: "*/2 * * * *"
  displayName: "Check deployments"
  branches:
      include:
      - master
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
          period=`date -u -d '24 hours ago' "+%Y-%m-%dT%H:%M:%S.%6N%:z"`
      
          last_modified=`aws elasticbeanstalk describe-environments --region us-east-1 | jq --arg s "$period" '.Environments | .[] | select((.EnvironmentName |contains ("qa")) and (.DateUpdated < $s))'`
          env_name=`echo "$last_modified" | jq -r .EnvironmentName`
      
          if [[ -n $last_modified ]]; then
              for i in $env_name;
              do
                  for j in qa{1..3};
                  do
                      if [[ $i =~ $j ]]; then
                      echo "Destroying $i"
                      terraform init -backend-config mapme-$j
                      terraform destroy -var-file mapme-$j
                      fi
                  done
              done
          else 
              echo "There are nothing to destroy"
          fi
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
  displayName: 'Autodestroy'
